server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgresql
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: EVENTS-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9001}

#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
