apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service-app
spec:
  selector:
    matchLabels:
      app: events-service-app
  template:
    metadata:
      labels:
        app: events-service-app
    spec:
      containers:
      - name: events-service-app
        image: IMAGE_URL/events-service
        ports:
        - containerPort: 8070
        env:
          - name: CONFIG_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: CONFIG_SERVER_URL
                name: config-cm 
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: postgresql-cm

---
apiVersion: v1
kind: Service
metadata:
  name: events-service-svc
spec:
  selector:
    app: events-service-app
  ports:
  - port: 80
    targetPort: 8070
        
